### ISSUE TITLE
Add SNMPv3 feature to the Shell

### ISSUE THREAD

**Issue by turkovda** [QualiSystems/F5-BIG-IP-Loadbalancer-Shell-2G#3]
### Issue details

SNMPv3 configuration is not supported.
![image](https://user-images.githubusercontent.com/59359491/93989360-79e00b00-fd92-11ea-8e66-76c7b711387d.png)

### Steps to reproduce

1. Configure SNMPv3 on inventory page

**Comment by anthony-poddubny** [comment]
done
